CREATE TABLE
  EMPREGADOS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    OCUPACAO TEXT NOT NULL,
    SALARIO INTEGER NOT NULL,
    COMISSAO INTEGER,
    DATA_CONTRATACAO TEXT,
    DEPARTAMENTO_ID INTEGER NOT NULL,
    GERENTE_ID INTEGER
  )